const LANGUAGES=[['ウェールズ語','cy'],['アルバニア語','sq'],['ジョージア語','ka'],['グジャラート語','gu'],['ベンガル語','bn'],['タミル語','ta'],['テルグ語','te'],['スワヒリ語','sw'],['ハイチ語','ht'],['エストニア語','et'],['ネパール語','ne'],['アフリカーンス語','af'],['インドネシア語','id'],['クメール語','km'],['ラオ語','lo'],['ラトビア語','lv'],['マラヤーラム語','ml'],['マラーティー語','mr']];
const API_BASE=(location.hostname==='localhost'||location.hostname==='127.0.0.1')?'http://127.0.0.1:8787':'https://SET_YOUR_WORKER_URL';
const $=s=>document.querySelector(s);const source=$('#source'),go=$('#go'),status=$('#status'),resultCard=$('#resultCard');let busy=false;
source.addEventListener('input',()=>$('#count').textContent=source.value.length);
function routeFor(n){const pool=[...LANGUAGES];for(let i=pool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}return pool.slice(0,n)}
async function translate(text,target){let last;for(let attempt=0;attempt<2;attempt++){try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),18000);const res=await fetch(`${API_BASE}/translate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,target}),signal:controller.signal});clearTimeout(timer);if(!res.ok)throw Error('translation');const data=await res.json();if(typeof data.text!=='string'||!data.text.trim())throw Error('translation');return data.text}catch(e){last=e;if(!navigator.onLine)throw Error('offline')}}throw last||Error('translation')}
async function play(){if(busy)return;const original=source.value.trim();if(!original){status.textContent='日本語を書いてから押してね。';source.focus();return}if(!navigator.onLine){status.textContent='インターネットにつながったら遊べるよ。';return}busy=true;go.disabled=true;$('#again').disabled=true;status.textContent='ことばが世界を旅行中！';resultCard.hidden=false;$('#result').textContent='旅に出発！';const langs=routeFor(Number($('#level').value));const journey=[];let text=original;try{for(let i=0;i<langs.length;i++){status.textContent=`ことばが世界を旅行中！ ${i+1} / ${langs.length}`+(i>=langs.length-2?'　もうすぐ日本へ帰ります！':'');text=await translate(text,langs[i][1]);journey.push({name:langs[i][0],text});$('#result').textContent=text;$('#route').textContent='日本語 → '+journey.map(x=>x.name).join(' → ')+' → 日本語';$('#steps').innerHTML=journey.map(x=>`<li><strong>${escapeHtml(x.name)}</strong><br>${escapeHtml(x.text)}</li>`).join('')}text=await translate(text,'ja');$('#result').textContent=text;$('#route').textContent='日本語 → '+journey.map(x=>x.name).join(' → ')+' → 日本語';status.textContent='日本に帰ってきたよ！'}catch(e){status.textContent=e.message==='offline'?'インターネットにつながったら遊べるよ。':'うまく翻訳できなかったよ。もう一回やってみよう！';if(journey.length){$('#result').textContent='あと少しだったのに…';$('#route').textContent='日本語 → '+journey.map(x=>x.name).join(' → ')}}finally{busy=false;go.disabled=false;$('#again').disabled=false}}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
go.addEventListener('click',play);$('#again').addEventListener('click',play);window.addEventListener('offline',()=>{$('#offline').hidden=false});window.addEventListener('online',()=>{$('#offline').hidden=true});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
