import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const store=new Map(),calls=[];let failure=false;
const props={getProperty:k=>store.get(k)||null,setProperty:(k,v)=>store.set(k,v)};
const gas={console:{log(){}},PropertiesService:{getScriptProperties:()=>props},LockService:{getScriptLock:()=>({waitLock(){},tryLock:()=>true,releaseLock(){}})},ContentService:{MimeType:{JSON:'json'},createTextOutput:t=>({text:t,setMimeType(){return this}})},Utilities:{Charset:{UTF_8:'utf8'},sleep(){},getUuid:()=>crypto.randomUUID(),base64EncodeWebSafe:v=>Buffer.from(v).toString('base64url'),base64DecodeWebSafe:v=>Buffer.from(v,'base64url'),newBlob:v=>({getDataAsString:()=>Buffer.from(v).toString()}),computeHmacSha256Signature:(v,k)=>crypto.createHmac('sha256',k).update(v).digest()},LanguageApp:{translate:(text,source,target)=>{calls.push({text,source,target});if(failure)throw Error('private error');return text+'['+target+']'}}};
vm.createContext(gas);vm.runInContext(fs.readFileSync(new URL('../apps-script/Code.gs',import.meta.url),'utf8'),gas);gas.setupLanguages();assert.equal(JSON.parse(gas.doGet().text).ready,true);
const post=b=>JSON.parse(gas.doPost({postData:{contents:JSON.stringify(b)}}).text);
const story='昔々、あるところにおじいさんとおばあさんが住んでいました。\nおじいさんは山へしばかりに、おばあさんは川で洗濯に。\n\nある日、おばあさんは川で大きな桃をひろい、家に持って帰りました。';
for(const level of [3,5,8,12]){calls.length=0;store.delete('BUDGET');const start=post({action:'start',text:story,level,previousRoute:[]});assert(start.ok);assert.equal(new Set(start.route.map(x=>x.code)).size,level);let token=start.token,text=story;for(let i=0;i<=level;i++){const s=post({action:'step',token});assert(s.ok);assert.equal(calls.at(-1).text,text);assert.equal(calls.at(-1).source,i===0?'ja':start.route[i-1].code);assert.equal(calls.at(-1).target,i===level?'ja':start.route[i].code);assert.equal(s.done,i===level);token=s.token;text=s.text}assert.equal(calls.length,level+1);console.log('PASS simulated LanguageApp chain',level)}
store.delete('BUDGET');let previousRoute=[];for(let i=0;i<4;i++){const start=post({action:'start',text:story,level:5,previousRoute});const next=start.route.map(x=>x.code);assert.notDeepEqual(next,previousRoute);previousRoute=next}
for(const b of [{action:'start',text:'x'.repeat(501),level:5,previousRoute:[]},{action:'start',text:23,level:5,previousRoute:[]},{action:'start',text:'x',level:13,previousRoute:[]},{action:'start',text:'x',level:5,previousRoute:['en']},{action:'step',token:'bad'},{action:'step',token:'bad',target:'en'}])assert.equal(post(b).ok,false);
store.delete('BUDGET');const token=post({action:'start',text:'x',level:3,previousRoute:[]}).token;assert.equal(post({action:'step',token:token+'x'}).ok,false);failure=true;calls.length=0;assert.equal(post({action:'step',token}).ok,false);assert.equal(calls.length,2);failure=false;
store.set('BUDGET',JSON.stringify({minute:Date.now(),day:Date.now(),requests:80,calls:0,starts:0}));assert.equal(post({action:'probe'}).ok,false);store.delete('BUDGET');
assert(![...store.values()].some(x=>x.includes(story)));console.log('PASS invalid input, signed token, retry, rate limit, no persistent text');
// Integrated frontend state test. LanguageApp and DOM are test doubles, not real services.
const els=new Map();const el=()=>({value:'',textContent:'',hidden:true,disabled:false,open:false,children:[],listeners:{},addEventListener(n,f){this.listeners[n]=f},append(...x){this.children.push(...x)},replaceChildren(){this.children=[]}});
const document={querySelector:s=>{if(!els.has(s))els.set(s,el());return els.get(s)},createElement:el,createTextNode:text=>({textContent:text})};document.querySelector('#source').value=story;document.querySelector('#level').value='5';
let sent=0,bodySent=[],networkFail=false;
const navigator={onLine:true},events={};const front={document,navigator,window:{BACKEND_URL:'https://script.google.com/macros/s/TEST/exec',addEventListener:(n,f)=>events[n]=f},AbortController,setTimeout,clearTimeout,fetch:async(url,o)=>{sent++;bodySent.push(JSON.parse(o.body));assert(url.endsWith('/exec'));assert.equal(o.method,'POST');assert.equal(o.mode,'cors');assert.equal(o.headers['Content-Type'],'text/plain;charset=UTF-8');assert.equal(o.credentials,'omit');assert(!url.includes(encodeURIComponent(story)));if(networkFail)throw Error('private');return Response.json(post(JSON.parse(o.body)))}};
vm.createContext(front);vm.runInContext(fs.readFileSync(new URL('../app.js',import.meta.url),'utf8'),front);
assert(document.querySelector('#offline').hidden);const pending=document.querySelector('#go').listeners.click();await document.querySelector('#go').listeners.click();await pending;assert.equal(sent,8);assert.equal(bodySent[0].action,'probe');assert.equal(document.querySelector('#steps').children.length,7);assert.match(document.querySelector('#result').textContent,/\[ja\]$/);assert(!document.querySelector('#go').disabled);
navigator.onLine=false;events.offline();assert(!document.querySelector('#offline').hidden);await document.querySelector('#go').listeners.click();assert.equal(sent,8);navigator.onLine=true;events.online();assert(document.querySelector('#offline').hidden);
networkFail=true;await document.querySelector('#go').listeners.click();assert(!document.querySelector('#go').disabled);assert(!document.querySelector('#status').textContent.includes('private'));console.log('PASS frontend POST contract, preflight avoidance, chain display, double-click, offline recovery, API failure');
